development:
  adapter: async

test:
  adapter: test

production:
  # adapter: redis
  # url: <%= ENV['REDIS_URL'] %>
  # channel_prefix: codenames_production
  adapter: postgres
  url: <%= ENV['DATABASE_URL'] %>
